"""Recreate pserson table.

Revision ID: 321bb84fc5cc
Revises: 835fb960607e
Create Date: 2024-08-09 20:28:00.248619

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '321bb84fc5cc'
down_revision: Union[str, None] = '835fb960607e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('PERSON',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('NAME', sa.String(), nullable=True),
    sa.Column('WEIGHT', sa.Integer(), nullable=True),
    sa.Column('HIGH', sa.Integer(), nullable=True),
    sa.Column('AGE', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('PERSON')
    # ### end Alembic commands ###
