"""Person table delete.

Revision ID: 835fb960607e
Revises: 466c6ecf4230
Create Date: 2024-08-09 20:26:34.080334

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '835fb960607e'
down_revision: Union[str, None] = '466c6ecf4230'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users2',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('PERSON')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('PERSON',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False),
    sa.Column('WEIGHT', sa.VARCHAR(collation='Japanese_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('HIGH', sa.DATETIME(), autoincrement=False, nullable=True),
    sa.Column('AGE', sa.VARCHAR(collation='Japanese_CI_AS'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='PK__PERSON__3213E83FE161D97B')
    )
    op.drop_table('users2')
    op.drop_table('users')
    # ### end Alembic commands ###
