"""Recreate Person table 

Revision ID: 00b30bc8319b
Revises: 8ccd3fdbbd2a
Create Date: 2024-08-09 20:41:41.647385

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '00b30bc8319b'
down_revision: Union[str, None] = '8ccd3fdbbd2a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('PERSON',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('NAME', sa.NVARCHAR(length=128), nullable=True),
    sa.Column('WEIGHT', sa.Integer(), nullable=True),
    sa.Column('HIGH', sa.Integer(), nullable=True),
    sa.Column('AGE', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('PERSON')
    # ### end Alembic commands ###
