"""import test.

Revision ID: 466c6ecf4230
Revises: afb20fc1b7e9
Create Date: 2024-08-09 20:19:36.858172

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '466c6ecf4230'
down_revision: Union[str, None] = 'afb20fc1b7e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('PERSON',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('WEIGHT', sa.String(), nullable=True),
    sa.Column('HIGH', sa.DateTime(), nullable=True),
    sa.Column('AGE', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('users2')
    op.drop_table('users')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(collation='Japanese_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('age', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='PK__users__3213E83FB83E1BAD')
    )
    op.create_table('users2',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(collation='Japanese_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('age', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='PK__users2__3213E83FF1E53AC6')
    )
    op.drop_table('PERSON')
    # ### end Alembic commands ###
