"""delete person

Revision ID: 8ccd3fdbbd2a
Revises: 1e97411032c3
Create Date: 2024-08-09 20:40:17.317806

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8ccd3fdbbd2a'
down_revision: Union[str, None] = '1e97411032c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('PERSON')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('PERSON',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False),
    sa.Column('NAME', sa.VARCHAR(length=128, collation='Japanese_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('WEIGHT', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('HIGH', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('AGE', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='PK__PERSON__3213E83F93972175')
    )
    # ### end Alembic commands ###
