"""String length change.

Revision ID: 1e97411032c3
Revises: 321bb84fc5cc
Create Date: 2024-08-09 20:33:19.804791

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e97411032c3'
down_revision: Union[str, None] = '321bb84fc5cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('PERSON', 'NAME',
               existing_type=sa.VARCHAR(collation='Japanese_CI_AS'),
               type_=sa.String(length=128),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('PERSON', 'NAME',
               existing_type=sa.String(length=128),
               type_=sa.VARCHAR(collation='Japanese_CI_AS'),
               existing_nullable=True)
    # ### end Alembic commands ###
